os: test

configuration: Release

init:
- appveyor version
- ps: Update-AppveyorBuild -Version "1.0 (Build 34)"

install:
- appveyor PushArtifact AppVeyorTest\AppVeyorTest.csproj

build:
  project: AppVeyorTest.sln
  verbosity: detailed
  
cache:
- packages -> **\packages.config

on_failure:
- ps: Get-EventLog AppVeyor -newest 10 | Format-List
