os: test

configuration: Release

init:
- appveyor version

install:
- appveyor PushArtifact AppVeyorTest\AppVeyorTest.csproj

build:
  project: AppVeyorTest.sln
  verbosity: detailed

after_build:
- appveyor PushArtifact AppVeyorTest.sln

artifacts:
- path: BuildScript

on_failure:
- ps: Get-EventLog AppVeyor -newest 10 | Format-List
