os: test

configuration: Release

init:
- appveyor version
- ps: Update-AppveyorBuild -Version "1.0 (Build 34)"

install:
- appveyor PushArtifact AppVeyorTest\AppVeyorTest.csproj

build:
  project: AppVeyorTest.sln
  verbosity: detailed

after_build:
- appveyor PushArtifact AppVeyorTest.sln

artifacts:
- path: BuildScript

on_finish:
- ps: Get-EventLog AppVeyor -newest 100 | Format-List
