os: Visual Studio 2015 RC

configuration: Release

build:
  project: AppVeyorTest.sln
  verbosity: detailed

cache:
  - packages -> **\packages.config

on_failure:
- ps: Get-EventLog AppVeyor -newest 10 | Format-List
