os: test

configuration: Release

init:
- ps: Restart-Computer

build:
  project: AppVeyorTest.sln
  verbosity: detailed

cache:
  - packages -> **\packages.config

on_failure:
- ps: Get-EventLog AppVeyor -newest 10 | Format-List
